services:

  backend:
    depends_on: ["postgres_db"]
    environment:
      - HIBERNATE_CONNECTION_DRIVER_CLASS=org.postgresql.Driver
      - HIBERNATE_CONNECTION_URL=jdbc:postgresql://postgres_db:5432/ucdb
      - HIBERNATE_CONNECTION_USER=uc_default_user
      - HIBERNATE_CONNECTION_PASSWORD=uc_default_password
    volumes: !reset []

  postgres_db:
    image: postgres:16.3
    environment:
      - POSTGRES_DB=ucdb
      - POSTGRES_USER=uc_default_user
      - POSTGRES_PASSWORD=uc_default_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
