name: unitycatalog

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - unitycatalog_local_data:/unitycatalog/etc

  ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  # Persist docker volume across container restarts
  unitycatalog_local_data:
