name: Build and Push Docker Images

on:
  push:
    # TODO: run on tags rather than branches
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'uc-cli.dockerfile'
      - '.github/workflows/docker.yml'

  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'uc-cli.dockerfile'
      - '.github/workflows/docker.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            image: unitycatalog
          - dockerfile: uc-cli.dockerfile
            image: uunitycatalog-cli

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest

        # NOTE: See here for an explanation of registry caching: https://tinyurl.com/4b8mfexr
        cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.image }}:buildcache
        cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.image }}:buildcache,mode=max
